name: ReVanced Test Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Download APKs from APKMirror
        run: ./download_apkmirror.sh

      - name: Test Build APKs
        run: |
          ./build_revanced.sh
          for filename in build/revanced-root.apk build/revanced-nonroot.apk build/revanced-music-root.apk build/revanced-music-nonroot.apk; do
            if [ -e "$filename" ]; then
              printf '"%s" exists\n' "$filename"
            else
              echo "APK build failed"
              exit 1
            fi
          done
          ls -la 
          echo tttt
          ls -la build
          
      - name: Upload to github actions
        uses: actions/upload-artifact@v3
        with:
          path: build/*.apk
          if-no-files-found: error

      - name: Clean1
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3


      - name: CleanUP
        run: |
          rm -rf build
